export const langs = [
	{ id: 0, name: 'React JS', icon: '/icons/react.jpeg' },
	{ id: 1, name: 'Node JS', icon: '/icons/nodejs.jpeg' },
	{ id: 2, name: 'Tailwind CSS', icon: '/icons/tailwindcss.jpeg' },
	{ id: 3, name: 'Typescript', icon: '/icons/typescript.png' },
	{ id: 3, name: 'GraphQl', icon: '/icons/graphql.png' },
	{ id: 4, name: 'Bootstrap', icon: '/icons/bootstrap.jpeg' },
	{ id: 5, name: 'HTML 5', icon: '/icons/html5.png' },
	{ id: 6, name: 'CSS 3', icon: '/icons/css3.png' },
	{ id: 7, name: 'Mongo DB', icon: '/icons/mongodb.jpeg' },
	{ id: 8, name: 'Git', icon: '/icons/git.png' },
	{ id: 9, name: 'MySQL', icon: '/icons/mysql.png' },
	{ id: 10, name: 'Sequelize', icon: '/icons/sequelize.png' },
	{ id: 11, name: 'Python', icon: '/icons/python.png' },
	{ id: 13, name: 'Docker', icon: '/icons/docker.png' },
	{ id: 14, name: 'Heroku', icon: '/icons/heroku.png' },
	{ id: 15, name: 'Bitbucket', icon: '/icons/bitbucket.png' },
	{ id: 16, name: 'AWS', icon: '/icons/aws.png' },
	{ id: 17, name: 'Yarn', icon: '/icons/yarn.png' },
]